project:
  type: book
  output-dir: _site
  resources:
    - "css/"
    - "js/"
    - "*.html"

book:
  title: "Understanding cities with open source tools and open data"
  author: "Shrividya Ravi"
  chapters:
    - index.qmd
    - pois.qmd
    - street_networks.qmd
    - buildings.qmd
    - user_data.qmd
    - references.qmd

bibliography: references.bib
csl: "ieee.csl"

format:
  html:
    toc: true
    theme: cosmo
    self-contained: true
    number-sections: true
    tbl-cap-location: top

execute:
  echo: false
  warning: false
editor: visual
